/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-02-14 08:23:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaReplyForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/slime/css/qnaWriteForm.css\">\r\n");
      out.write("\t<title>qna_답변작성</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form>\r\n");
      out.write("\t<input type=\"hidden\" id=\"pseq\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pseq }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t<input type=\"hidden\" id=\"pg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"qnaHeader\" style=\"width: 100%;\">\r\n");
      out.write("            <div class=\"write_header\"></div>\r\n");
      out.write("                <div class=\"header_line\">\r\n");
      out.write("                    <div class=\"border_name\" style=\"color : #4a4a4a; font-size:x-large\" >\r\n");
      out.write("                        <a href=\"/slime/qna/qnaBoardList\"><strong>Q&A</strong></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"btns\">\r\n");
      out.write("                        <input type=\"reset\" class=\"cancleQna\" value=\"다시작성\">\r\n");
      out.write("                        <button type=\"button\" id=\"QnaReplyBtn\" class=\"saveQna\">답변작성</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    <!---------------------->\r\n");
      out.write("    <!------글 작성 Form------>\r\n");
      out.write("    <!---------------------->\r\n");
      out.write("    <div class=\"qnaReplySection\">\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div class=\"qnaReplyForm\">\r\n");
      out.write("                <div class=\"editor_box\">\r\n");
      out.write("                    <div class=\"title_box\">\r\n");
      out.write("                            <div class=\"qna_subject\">\r\n");
      out.write("                                <input type=\"text\" class=\"qna_subject\" id=\"subject\" name=\"subject\" placeholder=\"제목\" autocomplete=\"off\">\r\n");
      out.write("                                <div id=\"subjectDiv\"></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"qnaBody\" style=\"padding-top: 15px;\">\r\n");
      out.write("                                <div class=\"txt_wrapper\">\r\n");
      out.write("                                    <input type=\"text\" class=\"qna_content\" id=\"content\" name=\"content\" placeholder=\"답변을 입력해주세요\" autocomplete=\"off\">\r\n");
      out.write("                                     <div id=\"contentDiv\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$('#QnaReplyBtn').click(function(){\r\n");
      out.write("\t$('#subjectDiv').empty();\r\n");
      out.write("\t$('#contentDiv').empty();\r\n");
      out.write("\r\n");
      out.write("\tif($('#subject').val()==''){\r\n");
      out.write("\t\t$('#subjectDiv').text('제목을 입력하세요');\r\n");
      out.write("\t\t$('#subjectDiv').css('color','black');\r\n");
      out.write("\t\t$('#subjectDiv').css('font-size','8pt');\r\n");
      out.write("\t\t$('#subjectDiv').css('font-weight','bold');\r\n");
      out.write("\t\t\r\n");
      out.write("\t}else if($('#content').val()==''){\r\n");
      out.write("\t\t$('#contentDiv').text('답변을 입력하세요')\r\n");
      out.write("\t\t$('#contentDiv').css('color','black')\r\n");
      out.write("\t\t$('#contentDiv').css('font-size','8pt')\r\n");
      out.write("\t\t$('#contentDiv').css('font-weight','bold');\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: 'post',\r\n");
      out.write("\t\t\turl: '/slime/qna/qnaReply',\r\n");
      out.write("\t\t\tdata: {'pseq': $('#pseq').val(), //원글번호\r\n");
      out.write("\t\t\t\t   'pg': $('#pg').val(), //원글이 있는 페이지번호\r\n");
      out.write("\t\t\t\t   'subject': $('#subject').val(),\r\n");
      out.write("\t\t\t\t   'content': $('#content').val()},\r\n");
      out.write("\t\t\tsuccess: function(){\r\n");
      out.write("\t\t\t\talert('답글쓰기 완료');\r\n");
      out.write("\t\t\t\tlocation.href='/slime/qna/qnaBoardList';\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror: function(err){\r\n");
      out.write("\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
