/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-02-01 05:45:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberWriteForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"memberWriteForm\" method=\"post\" action=\"/slime/member/write\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t    <h2 class=\"signUp-header\">회원가입</h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<article class=\"signUp-main\">\r\n");
      out.write("\t    <div class=\"signUp-name-form\">\r\n");
      out.write("\t        <input type=\"text\" class=\"sign-name\" name=\"member_name\" size=\"25\" placeholder=\"이름\">\r\n");
      out.write("\t        <div id=\"nameDiv\"></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-id-form\">\r\n");
      out.write("\t        <input type=\"text\" class=\"member_id\" id=\"member_id\" name=\"member_id\" size=\"25\" placeholder=\"아이디\">\r\n");
      out.write("\t        <input type=\"button\" class=\"check-Btn\" value=\"중복체크\" id=\"checkBtn\"><br>\r\n");
      out.write("\t        <input type=\"hidden\" id=\"check\" value=\"\">\r\n");
      out.write("\t      <div id=\"idDiv\"></div>\r\n");
      out.write("\t      \r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-pwd-form\">\r\n");
      out.write("\t        <input type=\"password\" class=\"sign-pwd\" name=\"member_pw\" size=\"25\" placeholder=\"비밀번호\">\r\n");
      out.write("\t        <div id=\"pwdDiv\"></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-rePwd-form\">\r\n");
      out.write("\t        <input type=\"password\" class=\"sign-repwd\" name=\"repw\" size=\"25\" placeholder=\"비밀번호 재입력\">\r\n");
      out.write("\t        <div id=\"repwdDiv\"></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-email-form\">\r\n");
      out.write("\t        <input type=\"text\" class=\"sign-email1\" name=\"email1\" size=\"15\">\r\n");
      out.write("\t        @\r\n");
      out.write("\t        <input type=\"email\" class=\"sign-email2\" name=\"email2\" list=\"email2\" placeholder=\"직접입력\">\r\n");
      out.write("\t        <datalist id=\"email2\">\r\n");
      out.write("\t            <option value=\"gmail.com\">\r\n");
      out.write("\t            <option value=\"naver.com\">\r\n");
      out.write("\t            <option value=\"hanmail.net\">\r\n");
      out.write("\t        </datalist>\r\n");
      out.write("\t        <input type=\"button\" class=\"email-Btn\" value=\"이메일인증\" id=\"emailBtn\"><br>\r\n");
      out.write("\t         <input type=\"text\" class=\"check-email\" name=\"check-email\" placeholder=\"인증번호 입력\">\r\n");
      out.write("\t        <input type=\"button\" class=\"email-check-Btn\" value=\"인증번호확인\" id=\"emailCheckBtn\"><br>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-phone-form\">\r\n");
      out.write("\t        <select name=\"tel1\" class=\"sign-tel1\" style=\"width: 60px;\">\r\n");
      out.write("\t            <option value=\"010\">010\r\n");
      out.write("\t            <option value=\"011\">011\r\n");
      out.write("\t            <option value=\"019\">019\r\n");
      out.write("\t        </select>\r\n");
      out.write("\t         -\r\n");
      out.write("\t         <input type=\"text\" class=\"sign-tel2\" name=\"tel2\" size=\"5\">\r\n");
      out.write("\t         -\r\n");
      out.write("\t         <input type=\"text\" class=\"sign-tel3\" name=\"tel3\" size=\"5\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-address-form\">\r\n");
      out.write("\t        <input type=\"text\" class=\"sign-post\" id=\"postcode\" name=\"zipcode\" size=\"5\" readonly>\r\n");
      out.write("\t        <input type=\"button\" class=\"check-Post-Btn\" value=\"우편번호검색\" id=\"checkPostBtn\"><br>\r\n");
      out.write("\t        <input type=\"text\" class=\"sign-address\" id=\"address\" name=\"addr1\" size=\"40\"  readonly placeholder=\"주소\"><br>\r\n");
      out.write("\t        <input type=\"text\" class=\"sign-detail\" id=\"detailAddress\" name=\"addr2\" size=\"40\" placeholder=\"상세주소\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t    <div class=\"signUp-btn-box\">\r\n");
      out.write("\t        <input type=\"button\" id=\"writeBtn\" value=\"회원가입\">\r\n");
      out.write("\t        <input type=\"reset\" value=\"다시작성\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</article>\r\n");
      out.write("\r\n");
      out.write("\t<input type=\"hidden\" name=\"email_key\" value=\"0\">\t<!— 일단 0으로 처리 —>\r\n");
      out.write("\t<input type=\"hidden\" name=\"admin_yn\" value=\"0\">\t\t<!— 관리자는 1, 그 외는 0 —>\t\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\t<!— 위아래 순서가 바뀌면 안된다 —>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/slime/js/member.js?ver=1\"></script>\t<!— 위아래 순서가 바뀌면 안된다 —>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
