/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-02-13 05:50:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.map;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class location_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/SlimeProject2/gaebokchi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/uzuslime/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1609668270889L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/slime/css/grid.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/slime/css/normalize.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/slime/css/index.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/slime/css/location.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,200;0,300;0,400;0,500;1,300;1,400&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<title>찾아오시는 길</title>\r\n");
      out.write("<!---------------------->\r\n");
      out.write("<!--------HAEDER-------->\r\n");
      out.write("<!---------------------->\r\n");
      out.write("<header>\r\n");
      out.write("\t<nav id=\"nav\">    \t\t\t\r\n");
      out.write("\t\t<a href=\"/slime/index.jsp\"><img src=\"/slime/image/logo.jpg\" alt=\"slime logo\" class=\"logo\"></a>\r\n");
      out.write("\t\t<div style=\"margin-bottom: 2%;\">");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../indexNav.jsp", out, false);
      out.write("</div>      \r\n");
      out.write("\t</nav>\r\n");
      out.write("</header>  \r\n");
      out.write("\r\n");
      out.write("<!--------------------------->\r\n");
      out.write("<!--------SIDEBAR-MENU------->\r\n");
      out.write("<!--------------------------->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../sideMenu.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!---------------------->\r\n");
      out.write("<!-------동영상------->\r\n");
      out.write("<!---------------------->\r\n");
      out.write("<div class=\"videobox\">\r\n");
      out.write("\t<video muted autoplay loop style=\"height:5%;\">\r\n");
      out.write("\t    <source src=\"/slime/videos/white.mp4\" type=\"video/mp4\">\r\n");
      out.write("\t</video>\r\n");
      out.write("\r\n");
      out.write("\t<!---------------------->\r\n");
      out.write("\t<!-------location------->\r\n");
      out.write("\t<!---------------------->\r\n");
      out.write("\t<div class=\"location-text\">\r\n");
      out.write("\t\t\t\t<h3><strong>찾아오시는 길</strong></h3>\r\n");
      out.write("\t\t\t\t<hr style=\"width:800px;\">\r\n");
      out.write("\t\t\t\t<p><strong>ʕっ•ﻌ•ʔっ</strong></p>\r\n");
      out.write("\t\t\t\t<p>우주 슬라임의 모든 제품들을 직접 함께 만들어 볼 고객님,</p>\r\n");
      out.write("\t\t\t\t<p>슬라임을 만들어 본 적이 없는데 </p>\r\n");
      out.write("\t\t\t\t<p>혼자는 만들어보기 두렵고 도움이 필요한 고객님,</p>\r\n");
      out.write("\t\t\t\t<p>나만의 슬라임을 만들고 싶은 고객님은</p>\r\n");
      out.write("\t\t\t\t<p>아래의 주소를 참고해서 저희 매장을 방문해주세요</p>\r\n");
      out.write("\t\t\t\t<hr style=\"width:800px;\">\r\n");
      out.write("\t\t\t\t<p><strong>(ू•ᴗ•ू)!</strong></p>\r\n");
      out.write("\t\t\t\t<p>*매장을 방문하시기 전에 예약전화를 주시면 감사하겠습니다</p>\r\n");
      out.write("\t\t\t\t<p></p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div><!--videobox-->\r\n");
      out.write("\r\n");
      out.write("<!---------------------->\r\n");
      out.write("<!-------location------->\r\n");
      out.write("<!---------------------->\r\n");
      out.write("<div class=\"locationTotal\">\r\n");
      out.write("\t<div class=\"location\">\r\n");
      out.write("\t\t<!-- * 카카오맵 - 지도퍼가기 -->\r\n");
      out.write("\t\t<!-- 1. 지도 노드 -->\r\n");
      out.write("\t\t<div id=\"daumRoughmapContainer1612931646259\" class=\"root_daum_roughmap root_daum_roughmap_landing\" style=\"margin:10px;\"></div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--\r\n");
      out.write("\t\t\t2. 설치 스크립트\r\n");
      out.write("\t\t\t* 지도 퍼가기 서비스를 2개 이상 넣을 경우, 설치 스크립트는 하나만 삽입합니다.\r\n");
      out.write("\t\t-->\r\n");
      out.write("\t\t<script charset=\"UTF-8\" class=\"daum_roughmap_loader_script\" src=\"https://ssl.daumcdn.net/dmaps/map_js_init/roughmapLoader.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- 3. 실행 스크립트 -->\r\n");
      out.write("\t\t<script charset=\"UTF-8\">\r\n");
      out.write("\t\t\tnew daum.roughmap.Lander({\r\n");
      out.write("\t\t\t\t\"timestamp\" : \"1612931646259\",\r\n");
      out.write("\t\t\t\t\"key\" : \"24dyg\",\r\n");
      out.write("\t\t\t\t\"mapWidth\" : \"400\",\r\n");
      out.write("\t\t\t\t\"mapHeight\" : \"300\"\r\n");
      out.write("\t\t\t}).render();\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"location-text2\">\r\n");
      out.write("\t\t<p>[우주슬라임 오프라인 매장 주소 ]</p>\r\n");
      out.write("\t\t<p>- 서울 서초구 강남대로 459 (우)06611</p>\r\n");
      out.write("\t\t<p>- 백암빌딩 구관 2층 201호</p>\r\n");
      out.write("\t\t<p>- 지번 : 서초동 1303-34</p>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <div class=\"col span-1-of-4\">\r\n");
      out.write("            <ul class=\"footer-nav\">\r\n");
      out.write("                <h3><strong>우주슬라임</strong></h3>\r\n");
      out.write("                <p>상호명 : 핌크리에이티브</p>\r\n");
      out.write("                <p>대표자 : 신동환</p>\r\n");
      out.write("                <p>사업자등록번호 : 105-88-00230</p>\r\n");
      out.write("                <p>서울시 강남구 테헤란로83길 18,<br> 매직킹덤빌딩 10층</p>\r\n");
      out.write("                <p>통신파매업 제2015-서울강남-03630호</p>\r\n");
      out.write("                <p>사업자 정보확인</p>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col span-1-of-4\">\r\n");
      out.write("            <div class=\"footer-nav\">\r\n");
      out.write("                <h3><strong>무통장입금</strong></h3>\r\n");
      out.write("                <p>137-090127-01-022</p>\r\n");
      out.write("                <p>기업은행</p>\r\n");
      out.write("                <p>(주)핌크리에이티브</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col span-1-of-4\">\r\n");
      out.write("            <div class=\"footer-nav\">\r\n");
      out.write("                <h3><strong>고객센터</strong></h3>\r\n");
      out.write("                <p>010-2104-2264</p>\r\n");
      out.write("                <p>카카오톡 : uzuslime</p>\r\n");
      out.write("                <p>월요일 - 금요일 AM 10:00 - 19:00</p>\r\n");
      out.write("                <p>문의 : uzuslime@naver.com<br><br></p>\r\n");
      out.write("                <p>[반품/교환지 주소]</p>\r\n");
      out.write("                <p>경기도 김포시 양촌읍 학운리 3342</p>\r\n");
      out.write("                <p>(주)철저한 물류. 우주슬라임</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col span-1-of-4\">\r\n");
      out.write("            <div class=\"social-links\">\r\n");
      out.write("                <li><a href=\"https://www.facebook.com/uzuslime\"><ion-icon class=\"ion-social-facebook\" name=\"logo-facebook\"></ion-icon></a></li>\r\n");
      out.write("                <li><a href=\"https://twitter.com/?lang=ko\"><ion-icon class=\"ion-social-twitter\" name=\"logo-twitter\"></ion-icon></a></li>\r\n");
      out.write("                <li><a href=\"https://www.instagram.com/uzuslime/\"><ion-icon class=\"ion-social-googleplus\" name=\"logo-google\"></ion-icon></a></li>\r\n");
      out.write("                <li><a href=\"https://www.instagram.com/uzuslime/\"><ion-icon class=\"ion-social-instagram\" name=\"logo-instagram\"></ion-icon></a></li>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row \" id=\"row\">\r\n");
      out.write("        <p>\r\n");
      out.write("            copyright 2018. <strong>우주슬라임</strong> All rights reserved\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>\r\n");
      out.write("            이용약관 <i class=\"ion-ios-heart\" style=\"color: #ea0000; padding: 0 3px;\"></i> 개인정보처리방침\r\n");
      out.write("        </p>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("\tdocument.getElementById('mySideNav').style.width = '250px';\r\n");
      out.write("}\r\n");
      out.write("function closeNav() {\r\n");
      out.write("\tdocument.getElementById('mySideNav').style.width = '0';\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://unpkg.com/ionicons@5.2.3/dist/ionicons.js\"> </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
